kafka:
  image: spotify/kafka
  environment:
    - KAFKA=localhost:9092
    - ZOOKEEPER=localhost:2181
  expose:
    - "2181"
    - "9092"

spark:
  image: sequenceiq/spark
  command: bash
  volumes:
    - .:/app
  links:
   - kafka
